<?php

declare(strict_types=1);

$table = 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci';

return [
    'up' => [
        "CREATE TABLE appointment_types (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            service_id BIGINT UNSIGNED NULL,
            slug VARCHAR(120) NOT NULL UNIQUE,
            title VARCHAR(190) NOT NULL,
            description TEXT NULL,
            duration_minutes SMALLINT UNSIGNED NOT NULL,
            formats JSON NOT NULL,
            slot_interval_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 30,
            buffer_before_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 0,
            buffer_after_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 15,
            lead_time_hours SMALLINT UNSIGNED NOT NULL DEFAULT 24,
            max_advance_days SMALLINT UNSIGNED NOT NULL DEFAULT 60,
            cancellation_window_hours SMALLINT UNSIGNED NOT NULL DEFAULT 48,
            reschedule_window_hours SMALLINT UNSIGNED NOT NULL DEFAULT 24,
            refund_on_cancel_percent TINYINT UNSIGNED NOT NULL DEFAULT 100,
            cancellation_policy TEXT NULL,
            reschedule_policy TEXT NULL,
            requires_payment TINYINT(1) NOT NULL DEFAULT 1,
            requires_approval TINYINT(1) NOT NULL DEFAULT 0,
            tax_label VARCHAR(60) NULL,
            tax_rate_bp INT UNSIGNED NOT NULL DEFAULT 0,
            tax_inclusive TINYINT(1) NOT NULL DEFAULT 1,
            is_active TINYINT(1) NOT NULL DEFAULT 0,
            is_public TINYINT(1) NOT NULL DEFAULT 1,
            sort_order INT NOT NULL DEFAULT 0,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            KEY appointment_types_service_idx (service_id, is_active),
            CONSTRAINT appointment_types_service_fk FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE SET NULL
        ) {$table}",

        "CREATE TABLE appointment_type_prices (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            appointment_type_id BIGINT UNSIGNED NOT NULL,
            currency CHAR(3) NOT NULL,
            amount_minor BIGINT UNSIGNED NOT NULL,
            UNIQUE KEY type_currency_unique (appointment_type_id, currency),
            CONSTRAINT prices_type_fk FOREIGN KEY (appointment_type_id) REFERENCES appointment_types(id) ON DELETE CASCADE
        ) {$table}",

        "CREATE TABLE availability_schedules (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            appointment_type_id BIGINT UNSIGNED NULL,
            weekday TINYINT UNSIGNED NOT NULL COMMENT 'ISO-8601: 1 = Monday … 7 = Sunday',
            start_time TIME NOT NULL,
            end_time TIME NOT NULL,
            timezone VARCHAR(64) NOT NULL,
            city_id INT UNSIGNED NULL,
            valid_from DATE NULL,
            valid_until DATE NULL,
            is_active TINYINT(1) NOT NULL DEFAULT 1,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            KEY availability_type_idx (appointment_type_id, is_active),
            CONSTRAINT availability_type_fk FOREIGN KEY (appointment_type_id) REFERENCES appointment_types(id) ON DELETE CASCADE,
            CONSTRAINT availability_city_fk FOREIGN KEY (city_id) REFERENCES cities(id) ON DELETE SET NULL
        ) {$table}",

        "CREATE TABLE unavailable_dates (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            appointment_type_id BIGINT UNSIGNED NULL,
            starts_at DATETIME NOT NULL,
            ends_at DATETIME NOT NULL,
            reason VARCHAR(255) NULL,
            created_by BIGINT UNSIGNED NULL,
            created_at DATETIME NOT NULL,
            KEY unavailable_range_idx (starts_at, ends_at),
            CONSTRAINT unavailable_type_fk FOREIGN KEY (appointment_type_id) REFERENCES appointment_types(id) ON DELETE CASCADE,
            CONSTRAINT unavailable_user_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
        ) {$table}",

        "CREATE TABLE consent_records (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            subject_type VARCHAR(40) NOT NULL,
            subject_id BIGINT UNSIGNED NULL,
            consent_type VARCHAR(40) NOT NULL,
            policy_version VARCHAR(20) NOT NULL,
            granted TINYINT(1) NOT NULL,
            ip_hash CHAR(64) NULL,
            user_agent_hash CHAR(64) NULL,
            created_at DATETIME NOT NULL,
            KEY consent_subject_idx (subject_type, subject_id)
        ) {$table}",

        "CREATE TABLE applications (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            reference VARCHAR(24) NOT NULL UNIQUE,
            status ENUM('draft','submitted','under_review','info_requested','approved','invited','rejected','archived') NOT NULL DEFAULT 'draft',
            current_step TINYINT UNSIGNED NOT NULL DEFAULT 1,
            email_bidx CHAR(64) NULL,
            full_name_enc TEXT NULL,
            email_enc TEXT NULL,
            phone_enc TEXT NULL,
            city_enc TEXT NULL,
            professional_background_enc TEXT NULL,
            designation_enc TEXT NULL,
            organization_enc TEXT NULL,
            core_objective_enc TEXT NULL,
            preferred_availability_enc TEXT NULL,
            referral_details_enc TEXT NULL,
            confidential_notes_enc TEXT NULL,
            admin_notes_enc TEXT NULL,
            info_request_enc TEXT NULL,
            country CHAR(2) NULL,
            consultation_type VARCHAR(120) NULL,
            preferred_format ENUM('google_meet','phone','in_person') NULL,
            referral_source ENUM('referral','search','event','media','social','other') NULL,
            access_token_hash CHAR(64) NOT NULL,
            access_expires_at DATETIME NOT NULL,
            invite_token_hash CHAR(64) NULL,
            invite_expires_at DATETIME NULL,
            invited_appointment_type_id BIGINT UNSIGNED NULL,
            reviewed_by BIGINT UNSIGNED NULL,
            reviewed_at DATETIME NULL,
            submitted_at DATETIME NULL,
            retention_until DATETIME NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            KEY applications_status_idx (status, submitted_at),
            KEY applications_email_idx (email_bidx),
            UNIQUE KEY applications_invite_unique (invite_token_hash),
            CONSTRAINT applications_reviewer_fk FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
            CONSTRAINT applications_invite_type_fk FOREIGN KEY (invited_appointment_type_id) REFERENCES appointment_types(id) ON DELETE SET NULL
        ) {$table}",

        "CREATE TABLE appointments (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            reference VARCHAR(24) NOT NULL UNIQUE,
            appointment_type_id BIGINT UNSIGNED NOT NULL,
            application_id BIGINT UNSIGNED NULL,
            status ENUM('pending_application','awaiting_approval','pending_payment','payment_verification','confirmed','rescheduled','cancelled','completed','payment_failed','refunded') NOT NULL,
            starts_at DATETIME NOT NULL,
            ends_at DATETIME NOT NULL,
            client_timezone VARCHAR(64) NOT NULL,
            format ENUM('google_meet','phone','in_person') NOT NULL,
            city_id INT UNSIGNED NULL,
            client_email_bidx CHAR(64) NOT NULL,
            client_name_enc TEXT NOT NULL,
            client_email_enc TEXT NOT NULL,
            client_phone_enc TEXT NULL,
            notes_enc TEXT NULL,
            meet_url_enc TEXT NULL,
            currency CHAR(3) NULL,
            amount_minor BIGINT UNSIGNED NOT NULL DEFAULT 0,
            tax_minor BIGINT UNSIGNED NOT NULL DEFAULT 0,
            total_minor BIGINT UNSIGNED NOT NULL DEFAULT 0,
            access_token_hash CHAR(64) NOT NULL,
            idempotency_key VARCHAR(64) NULL,
            google_event_id VARCHAR(191) NULL,
            calendar_sync_status ENUM('not_required','pending','synced','failed') NOT NULL DEFAULT 'pending',
            calendar_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
            calendar_last_error VARCHAR(255) NULL,
            reschedule_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
            cancellation_reason VARCHAR(500) NULL,
            created_by BIGINT UNSIGNED NULL,
            confirmed_at DATETIME NULL,
            cancelled_at DATETIME NULL,
            completed_at DATETIME NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            KEY appointments_status_idx (status, starts_at),
            KEY appointments_starts_idx (starts_at),
            KEY appointments_email_idx (client_email_bidx),
            UNIQUE KEY appointments_idempotency_unique (idempotency_key),
            CONSTRAINT appointments_type_fk FOREIGN KEY (appointment_type_id) REFERENCES appointment_types(id),
            CONSTRAINT appointments_application_fk FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE SET NULL,
            CONSTRAINT appointments_city_fk FOREIGN KEY (city_id) REFERENCES cities(id) ON DELETE SET NULL,
            CONSTRAINT appointments_creator_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
        ) {$table}",

        "CREATE TABLE appointment_slots (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            appointment_id BIGINT UNSIGNED NULL,
            appointment_type_id BIGINT UNSIGNED NULL,
            block_starts_at DATETIME NOT NULL COMMENT 'start minus buffer_before',
            block_ends_at DATETIME NOT NULL COMMENT 'end plus buffer_after',
            status ENUM('held','booked','released','blocked') NOT NULL,
            held_until DATETIME NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            UNIQUE KEY slots_appointment_unique (appointment_id),
            KEY slots_overlap_idx (status, block_starts_at, block_ends_at),
            CONSTRAINT slots_appointment_fk FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE CASCADE,
            CONSTRAINT slots_type_fk FOREIGN KEY (appointment_type_id) REFERENCES appointment_types(id) ON DELETE SET NULL
        ) {$table}",

        "CREATE TABLE reminder_jobs (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            appointment_id BIGINT UNSIGNED NOT NULL,
            offset_minutes INT UNSIGNED NOT NULL,
            channel ENUM('email') NOT NULL DEFAULT 'email',
            run_at DATETIME NOT NULL,
            status ENUM('pending','sent','cancelled','failed') NOT NULL DEFAULT 'pending',
            attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
            sent_at DATETIME NULL,
            last_error VARCHAR(255) NULL,
            created_at DATETIME NOT NULL,
            UNIQUE KEY reminder_unique (appointment_id, offset_minutes, channel, run_at),
            KEY reminder_due_idx (status, run_at),
            CONSTRAINT reminder_appointment_fk FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE CASCADE
        ) {$table}",
    ],
    'down' => [
        'DROP TABLE IF EXISTS reminder_jobs',
        'DROP TABLE IF EXISTS appointment_slots',
        'DROP TABLE IF EXISTS appointments',
        'DROP TABLE IF EXISTS applications',
        'DROP TABLE IF EXISTS consent_records',
        'DROP TABLE IF EXISTS unavailable_dates',
        'DROP TABLE IF EXISTS availability_schedules',
        'DROP TABLE IF EXISTS appointment_type_prices',
        'DROP TABLE IF EXISTS appointment_types',
    ],
];
