import { formatMoney } from '../../lib/format'
import { formatAdminDate, formatAdminDateTime } from '../lib/datetime'
import { FORMAT_LABEL } from '../lib/labels'
import { Badge, Notice } from '../ui/Primitives'
import { AudioFilePanel, EmailTemplatePanel, EventRegistrationsPanel } from './panels'
import { asBool } from './types'
import type { Option, ResourceDef, Row } from './types'

const opts = (map: Record<string, string>): Option[] => Object.entries(map).map(([value, label]) => ({ value, label }))

const PUBLISH = opts({ draft: 'Draft', published: 'Published' })
const YES_NO = opts({ '1': 'Yes', '0': 'No' })
const WEEKDAYS = opts({ '1': 'Monday', '2': 'Tuesday', '3': 'Wednesday', '4': 'Thursday', '5': 'Friday', '6': 'Saturday', '7': 'Sunday' })
const EVENT_CATEGORIES = opts({
  retreat: 'Retreat',
  full_moon: 'Full-moon gathering',
  amavasya: 'Amavasya (new moon)',
  keynote: 'Keynote',
  executive_gathering: 'Executive gathering',
  group_advisory: 'Group advisory',
  summit: 'Summit',
})
const AUDIO_CATEGORIES = opts({ guided_meditation: 'Guided meditation', sonic_healing: 'Sonic healing', vedic_chant: 'Vedic chant', catharsis: 'Catharsis', sample: 'Sample' })
const QUALIFICATION_KINDS = opts({
  qualification: 'Qualification',
  certification: 'Certification',
  experience: 'Experience',
  publication: 'Publication',
  interview: 'Interview',
  speaking: 'Speaking',
  award: 'Award',
})

const status = (row: Row, key = 'status') => {
  const s = String(row[key] ?? '')
  const tone = s === 'published' ? 'green' : s === 'cancelled' ? 'red' : s === 'draft' ? 'gold' : 'muted'
  return <Badge tone={tone}>{s || '—'}</Badge>
}
const flag = (on: boolean, yes: string, no?: string) => (on ? <Badge tone="green">{yes}</Badge> : no ? <Badge tone="muted">{no}</Badge> : null)

export const RESOURCES: ResourceDef[] = [
  // ------------------------------------------------------------------ scheduling
  {
    key: 'appointment-types',
    endpoint: '/admin/appointment-types',
    title: 'Consultation types',
    singular: 'Consultation type',
    permission: 'appointments.configure',
    group: 'Scheduling',
    description: 'What clients can book: duration, formats, pricing per currency, approval and policies.',
    search: true,
    filters: [{ name: 'is_active', label: 'Active', options: YES_NO }],
    titleOf: (r) => String(r.title),
    defaults: { duration_minutes: 60, formats: ['google_meet'], slot_interval_minutes: 30, max_advance_days: 60, lead_time_hours: 24, cancellation_window_hours: 48, reschedule_window_hours: 24, refund_on_cancel_percent: 100, is_active: true, is_public: false, requires_approval: true, requires_payment: true, tax_rate_bp: 0 },
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'duration_minutes', label: 'Duration', render: (r) => `${String(r.duration_minutes)} min` },
      { key: 'formats', label: 'Formats', render: (r) => ((r.formats as string[]) ?? []).map((f) => FORMAT_LABEL[f] ?? f).join(', ') },
      { key: 'prices', label: 'Fees', render: (r) => (asBool(r.requires_payment) ? ((r.prices as { currency: string; amount_minor: number }[]) ?? []).map((p) => formatMoney(p)).join(' · ') || 'No price set' : 'Complimentary') },
      {
        key: 'flags',
        label: 'Access',
        render: (r) => (
          <span className="flex flex-wrap gap-1">
            {flag(asBool(r.is_active), 'Active', 'Inactive')}
            {asBool(r.is_public) ? <Badge tone="blue">Public</Badge> : <Badge tone="neutral">Invitation</Badge>}
            {asBool(r.requires_approval) && <Badge tone="gold">Approval</Badge>}
          </span>
        ),
      },
    ],
    sections: [
      { title: 'Consultation', fields: ['title', 'slug', 'service_id', 'duration_minutes', 'description', 'formats'] },
      { title: 'Access & payment', fields: ['is_active', 'is_public', 'requires_approval', 'requires_payment', 'prices', 'tax_label', 'tax_rate_bp', 'tax_inclusive'] },
      { title: 'Scheduling rules', fields: ['slot_interval_minutes', 'lead_time_hours', 'max_advance_days', 'buffer_before_minutes', 'buffer_after_minutes', 'sort_order'] },
      { title: 'Policies', fields: ['cancellation_window_hours', 'reschedule_window_hours', 'refund_on_cancel_percent', 'cancellation_policy', 'reschedule_policy'] },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, maxLength: 190 },
      { name: 'slug', label: 'Slug', type: 'slug', required: true, slugFrom: 'title' },
      { name: 'service_id', label: 'Related service', type: 'relation', relation: { path: '/admin/services', label: 'title' } },
      { name: 'duration_minutes', label: 'Duration (minutes)', type: 'number', required: true, min: 15, max: 600 },
      { name: 'description', label: 'Description', type: 'textarea', maxLength: 5000 },
      { name: 'formats', label: 'Formats offered', type: 'checkboxes', required: true, options: opts(FORMAT_LABEL) },
      { name: 'is_active', label: 'Active (bookable)', type: 'boolean' },
      { name: 'is_public', label: 'Publicly bookable', type: 'boolean', hint: 'Off: only clients with a private invitation can book.' },
      { name: 'requires_approval', label: 'Requires an approved application', type: 'boolean' },
      { name: 'requires_payment', label: 'Requires payment', type: 'boolean' },
      { name: 'prices', label: 'Prices', type: 'prices' },
      { name: 'tax_label', label: 'Tax label', type: 'text', maxLength: 60, hint: 'Shown on receipts, e.g. GST or VAT. Confirm with your accountant.' },
      { name: 'tax_rate_bp', label: 'Tax rate (basis points)', type: 'number', min: 0, max: 5000, hint: '100 basis points = 1%. 1800 = 18%.' },
      { name: 'tax_inclusive', label: 'Prices include tax', type: 'boolean' },
      { name: 'slot_interval_minutes', label: 'Slot interval (minutes)', type: 'number', min: 5, max: 240 },
      { name: 'lead_time_hours', label: 'Minimum notice (hours)', type: 'number', min: 0, max: 720 },
      { name: 'max_advance_days', label: 'Bookable up to (days ahead)', type: 'number', min: 1, max: 365 },
      { name: 'buffer_before_minutes', label: 'Buffer before (minutes)', type: 'number', min: 0, max: 240 },
      { name: 'buffer_after_minutes', label: 'Buffer after (minutes)', type: 'number', min: 0, max: 240 },
      { name: 'sort_order', label: 'Sort order', type: 'number' },
      { name: 'cancellation_window_hours', label: 'Free cancellation until (hours before)', type: 'number', min: 0, max: 720 },
      { name: 'reschedule_window_hours', label: 'Rescheduling until (hours before)', type: 'number', min: 0, max: 720 },
      { name: 'refund_on_cancel_percent', label: 'Refund on timely cancellation (%)', type: 'number', min: 0, max: 100 },
      { name: 'cancellation_policy', label: 'Cancellation policy (shown to clients)', type: 'textarea', maxLength: 5000 },
      { name: 'reschedule_policy', label: 'Rescheduling policy (shown to clients)', type: 'textarea', maxLength: 5000 },
    ],
  },
  {
    key: 'availability',
    endpoint: '/admin/availability',
    title: 'Weekly availability',
    singular: 'Availability window',
    permission: 'appointments.configure',
    group: 'Scheduling',
    description: 'Recurring weekly hours when consultations can be booked. Leave the consultation type empty to apply to all types.',
    filters: [{ name: 'weekday', label: 'Day', options: WEEKDAYS }],
    titleOf: (r) => `${WEEKDAYS.find((w) => w.value === String(r.weekday))?.label ?? ''} ${String(r.start_time).slice(0, 5)}–${String(r.end_time).slice(0, 5)}`,
    defaults: { weekday: 1, start_time: '10:00', end_time: '17:00', timezone: 'Asia/Kolkata', is_active: true },
    columns: [
      { key: 'weekday', label: 'Day', render: (r) => WEEKDAYS.find((w) => w.value === String(r.weekday))?.label ?? String(r.weekday) },
      { key: 'hours', label: 'Hours', render: (r) => `${String(r.start_time).slice(0, 5)} – ${String(r.end_time).slice(0, 5)}` },
      { key: 'timezone', label: 'Time zone' },
      { key: 'valid', label: 'Valid', render: (r) => (r.valid_from || r.valid_until ? `${formatAdminDate(r.valid_from as string | null)} → ${formatAdminDate(r.valid_until as string | null)}` : 'Always') },
      { key: 'is_active', label: 'Status', render: (r) => flag(asBool(r.is_active), 'Active', 'Paused') },
    ],
    fields: [
      { name: 'weekday', label: 'Day of week', type: 'select', required: true, options: WEEKDAYS },
      { name: 'appointment_type_id', label: 'Consultation type', type: 'relation', relation: { path: '/admin/appointment-types', label: 'title', emptyLabel: 'All consultation types' } },
      { name: 'start_time', label: 'Start', type: 'time', required: true },
      { name: 'end_time', label: 'End', type: 'time', required: true },
      { name: 'timezone', label: 'Time zone', type: 'timezone', required: true },
      { name: 'city_id', label: 'City (in-person)', type: 'relation', relation: { path: '/admin/cities', label: 'name', emptyLabel: 'Any / online' } },
      { name: 'valid_from', label: 'Valid from', type: 'date' },
      { name: 'valid_until', label: 'Valid until', type: 'date' },
      { name: 'is_active', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'unavailable-dates',
    endpoint: '/admin/unavailable-dates',
    title: 'Unavailable dates',
    singular: 'Blocked period',
    permission: 'appointments.configure',
    group: 'Scheduling',
    description: 'Travel, retreats and personal time. Blocks new bookings without affecting existing ones.',
    titleOf: (r) => String(r.reason || 'Blocked period'),
    columns: [
      { key: 'reason', label: 'Reason', render: (r) => String(r.reason || 'Blocked period') },
      { key: 'starts_at', label: 'From', render: (r) => formatAdminDateTime(r.starts_at as string) },
      { key: 'ends_at', label: 'Until', render: (r) => formatAdminDateTime(r.ends_at as string) },
    ],
    fields: [
      { name: 'starts_at', label: 'From', type: 'datetime', required: true },
      { name: 'ends_at', label: 'Until', type: 'datetime', required: true },
      { name: 'appointment_type_id', label: 'Consultation type', type: 'relation', relation: { path: '/admin/appointment-types', label: 'title', emptyLabel: 'All consultation types' } },
      { name: 'reason', label: 'Internal note', type: 'text', maxLength: 255, hint: 'Not shown to clients.' },
    ],
  },
  {
    key: 'cities',
    endpoint: '/admin/cities',
    title: 'Cities',
    singular: 'City',
    permission: 'content.manage',
    group: 'Scheduling',
    description: 'Locations offered for in-person consultations and gatherings.',
    titleOf: (r) => String(r.name),
    defaults: { is_active: true, timezone: 'Asia/Kolkata', country: 'IN' },
    columns: [
      { key: 'name', label: 'City' },
      { key: 'country', label: 'Country' },
      { key: 'timezone', label: 'Time zone' },
      { key: 'is_active', label: 'Status', render: (r) => flag(asBool(r.is_active), 'Active', 'Hidden') },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true, maxLength: 120 },
      { name: 'country', label: 'Country code', type: 'text', required: true, maxLength: 2, hint: 'Two-letter ISO code, e.g. IN, AE, GB.' },
      { name: 'timezone', label: 'Time zone', type: 'timezone', required: true },
      { name: 'sort_order', label: 'Sort order', type: 'number' },
      { name: 'is_active', label: 'Active', type: 'boolean' },
    ],
  },

  // ------------------------------------------------------------------ content
  {
    key: 'pages',
    endpoint: '/admin/pages',
    title: 'Pages',
    singular: 'Page',
    permission: 'content.manage',
    group: 'Content',
    description: 'Home and section introductions (structured fields) and legal pages (rich text).',
    search: true,
    filters: [
      { name: 'type', label: 'Type', options: opts({ page: 'Page', legal: 'Legal' }) },
      { name: 'status', label: 'Status', options: PUBLISH },
    ],
    notice: <Notice tone="warn">Legal pages must be reviewed by a qualified professional before publishing. Do not claim regulatory compliance without that review.</Notice>,
    titleOf: (r) => String(r.title),
    defaults: { type: 'page', status: 'draft' },
    publicPath: (r) => (r.status !== 'published' ? null : r.slug === 'home' ? '/' : r.type === 'legal' ? `/legal/${String(r.slug)}` : `/${String(r.slug)}`),
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'slug', label: 'Slug' },
      { key: 'type', label: 'Type', render: (r) => <Badge tone={r.type === 'legal' ? 'blue' : 'neutral'}>{String(r.type)}</Badge> },
      { key: 'status', label: 'Status', render: (r) => status(r) },
      { key: 'updated_at', label: 'Updated', render: (r) => formatAdminDateTime(r.updated_at as string) },
    ],
    sections: [
      { title: 'Page', fields: ['title', 'slug', 'type', 'status'] },
      { title: 'Body', fields: ['body'] },
      { title: 'Structured sections', fields: ['sections'] },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, maxLength: 255 },
      { name: 'slug', label: 'Slug', type: 'slug', required: true, slugFrom: 'title' },
      { name: 'type', label: 'Type', type: 'select', required: true, options: opts({ page: 'Page', legal: 'Legal' }) },
      { name: 'status', label: 'Status', type: 'select', required: true, options: PUBLISH },
      { name: 'body', label: 'Body', type: 'richtext' },
      { name: 'sections', label: 'Sections', type: 'structured', hint: 'Plain text only — markup is removed. Images are chosen from the media library.' },
    ],
  },
  {
    key: 'services',
    endpoint: '/admin/services',
    title: 'Services',
    singular: 'Service',
    permission: 'content.manage',
    group: 'Content',
    description: 'The disciplines presented on the Practice pages.',
    search: true,
    filters: [{ name: 'is_published', label: 'Published', options: YES_NO }],
    titleOf: (r) => String(r.title),
    defaults: { booking_mode: 'application', is_published: false },
    publicPath: (r) => (asBool(r.is_published) ? `/practice/${String(r.slug)}` : null),
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'booking_mode', label: 'Booking', render: (r) => String(r.booking_mode) },
      { key: 'is_published', label: 'Status', render: (r) => flag(asBool(r.is_published), 'Published', 'Hidden') },
      { key: 'sort_order', label: 'Order' },
    ],
    sections: [
      { title: 'Service', fields: ['title', 'slug', 'numeral', 'subtitle', 'category_id', 'booking_mode', 'duration_label', 'price_display', 'summary', 'cover_media_id', 'is_published', 'is_featured', 'sort_order'] },
      { title: 'Content', fields: ['body', 'highlights', 'offerings'] },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, maxLength: 190 },
      { name: 'slug', label: 'Slug', type: 'slug', required: true, slugFrom: 'title' },
      { name: 'numeral', label: 'Numeral', type: 'text', maxLength: 8, hint: 'e.g. I, II, III.' },
      { name: 'subtitle', label: 'Subtitle', type: 'text', maxLength: 255 },
      { name: 'category_id', label: 'Category', type: 'relation', relation: { path: '/admin/service-categories', label: 'name' } },
      { name: 'booking_mode', label: 'How clients engage', type: 'select', required: true, options: opts({ application: 'By application', direct: 'Direct booking', inquiry: 'Enquiry' }) },
      { name: 'duration_label', label: 'Duration label', type: 'text', maxLength: 120, hint: 'e.g. 90-minute sessions.' },
      { name: 'price_display', label: 'Price display', type: 'text', maxLength: 120, hint: 'e.g. “On request”. Leave empty to hide.' },
      { name: 'summary', label: 'Summary', type: 'textarea', required: true, maxLength: 1000 },
      { name: 'cover_media_id', label: 'Cover image', type: 'media' },
      { name: 'is_published', label: 'Published', type: 'boolean' },
      { name: 'is_featured', label: 'Featured on home page', type: 'boolean' },
      { name: 'sort_order', label: 'Sort order', type: 'number' },
      { name: 'body', label: 'Body', type: 'richtext' },
      { name: 'highlights', label: 'Highlights', type: 'structured', template: '' },
      { name: 'offerings', label: 'Offerings', type: 'structured', template: { title: '', description: '' } },
    ],
  },
  {
    key: 'service-categories',
    endpoint: '/admin/service-categories',
    title: 'Service categories',
    singular: 'Service category',
    permission: 'content.manage',
    group: 'Content',
    titleOf: (r) => String(r.name),
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'slug', label: 'Slug' },
      { key: 'sort_order', label: 'Order' },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true, maxLength: 190 },
      { name: 'slug', label: 'Slug', type: 'slug', required: true, slugFrom: 'name' },
      { name: 'description', label: 'Description', type: 'textarea', maxLength: 2000 },
      { name: 'sort_order', label: 'Sort order', type: 'number' },
    ],
  },
  {
    key: 'qualifications',
    endpoint: '/admin/qualifications',
    title: 'Qualifications & credentials',
    singular: 'Credential',
    permission: 'content.manage',
    group: 'Content',
    description: 'Shown on the practitioner page. Enter only verifiable facts; add a link to a source where one exists.',
    search: true,
    filters: [{ name: 'kind', label: 'Kind', options: QUALIFICATION_KINDS }],
    titleOf: (r) => String(r.title),
    defaults: { kind: 'qualification', is_published: false },
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'kind', label: 'Kind' },
      { key: 'institution', label: 'Institution' },
      { key: 'year', label: 'Year' },
      { key: 'is_published', label: 'Status', render: (r) => flag(asBool(r.is_published), 'Published', 'Hidden') },
    ],
    fields: [
      { name: 'practitioner_id', label: 'Practitioner', type: 'practitioner', required: true },
      { name: 'kind', label: 'Kind', type: 'select', required: true, options: QUALIFICATION_KINDS },
      { name: 'title', label: 'Title', type: 'text', required: true, maxLength: 255 },
      { name: 'institution', label: 'Institution / publisher', type: 'text', maxLength: 255 },
      { name: 'year', label: 'Year', type: 'number', min: 1900, max: 2100 },
      { name: 'url', label: 'Verification link', type: 'url', maxLength: 500 },
      { name: 'description', label: 'Description', type: 'textarea', maxLength: 5000 },
      { name: 'sort_order', label: 'Sort order', type: 'number' },
      { name: 'is_published', label: 'Published', type: 'boolean' },
    ],
  },
  {
    key: 'blogs',
    endpoint: '/admin/blogs',
    title: 'Journal',
    singular: 'Article',
    permission: 'content.manage',
    group: 'Content',
    search: true,
    filters: [{ name: 'status', label: 'Status', options: opts({ draft: 'Draft', published: 'Published', archived: 'Archived' }) }],
    titleOf: (r) => String(r.title),
    defaults: { status: 'draft' },
    publicPath: (r) => (r.status === 'published' ? `/journal/${String(r.slug)}` : null),
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'status', label: 'Status', render: (r) => status(r) },
      { key: 'published_at', label: 'Published', render: (r) => formatAdminDate(r.published_at as string | null) },
      { key: 'reading_minutes', label: 'Read', render: (r) => (r.reading_minutes ? `${String(r.reading_minutes)} min` : '—') },
    ],
    sections: [
      { title: 'Article', fields: ['title', 'slug', 'category_id', 'status', 'published_at', 'tags', 'excerpt', 'cover_media_id'] },
      { title: 'Body', fields: ['body'] },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, maxLength: 255 },
      { name: 'slug', label: 'Slug', type: 'slug', required: true, slugFrom: 'title' },
      { name: 'category_id', label: 'Category', type: 'relation', relation: { path: '/admin/blog-categories', label: 'name' } },
      { name: 'status', label: 'Status', type: 'select', required: true, options: opts({ draft: 'Draft', published: 'Published', archived: 'Archived' }) },
      { name: 'published_at', label: 'Publication date', type: 'datetime', hint: 'Leave empty to use the moment it is first published.' },
      { name: 'tags', label: 'Tags', type: 'tags', hint: 'Comma-separated.' },
      { name: 'excerpt', label: 'Excerpt', type: 'textarea', maxLength: 1000 },
      { name: 'cover_media_id', label: 'Cover image', type: 'media' },
      { name: 'body', label: 'Body', type: 'richtext' },
    ],
  },
  {
    key: 'blog-categories',
    endpoint: '/admin/blog-categories',
    title: 'Journal categories',
    singular: 'Journal category',
    permission: 'content.manage',
    group: 'Content',
    titleOf: (r) => String(r.name),
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'slug', label: 'Slug' },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true, maxLength: 190 },
      { name: 'slug', label: 'Slug', type: 'slug', required: true, slugFrom: 'name' },
      { name: 'description', label: 'Description', type: 'textarea', maxLength: 2000 },
    ],
  },
  {
    key: 'events',
    endpoint: '/admin/events',
    title: 'Gatherings',
    singular: 'Gathering',
    permission: 'events.manage',
    group: 'Content',
    description: 'Retreats, moon circles, keynotes and executive gatherings, with registrations.',
    search: true,
    filters: [
      { name: 'status', label: 'Status', options: opts({ draft: 'Draft', published: 'Published', cancelled: 'Cancelled', archived: 'Archived' }) },
      { name: 'category', label: 'Category', options: EVENT_CATEGORIES },
    ],
    titleOf: (r) => String(r.title),
    defaults: { status: 'draft', registration_mode: 'application', category: 'retreat', timezone: 'Asia/Kolkata', waitlist_enabled: true, tax_rate_bp: 0, tax_inclusive: true, cancellation_window_hours: 168, refund_on_cancel_percent: 100 },
    publicPath: (r) => (r.status === 'published' || r.status === 'cancelled' ? `/gatherings/${String(r.slug)}` : null),
    panels: [EventRegistrationsPanel],
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'starts_at', label: 'Starts', render: (r) => formatAdminDateTime(r.starts_at as string, r.timezone as string) },
      { key: 'registration_mode', label: 'Registration' },
      {
        key: 'seats',
        label: 'Places',
        render: (r) =>
          r.seat_quota ? `${String(r.seats_taken ?? 0)} / ${String(r.seat_quota)}${Number(r.waitlist_count) > 0 ? ` · ${String(r.waitlist_count)} waiting` : ''}` : `${String(r.seats_taken ?? 0)} · no limit`,
      },
      { key: 'prices', label: 'Contribution', render: (r) => ((r.prices as { currency: string; amount_minor: number }[]) ?? []).map((p) => formatMoney(p)).join(' · ') || 'None' },
      { key: 'status', label: 'Status', render: (r) => status(r) },
    ],
    sections: [
      { title: 'Gathering', fields: ['title', 'slug', 'category', 'status', 'is_featured', 'summary', 'cover_media_id'] },
      { title: 'When & where', fields: ['timezone', 'city_id', 'starts_at', 'ends_at', 'venue', 'address'] },
      { title: 'Registration', fields: ['registration_mode', 'registration_opens_at', 'registration_closes_at', 'seat_quota', 'waitlist_enabled', 'requirements'] },
      { title: 'Contribution', fields: ['prices', 'tax_label', 'tax_rate_bp', 'tax_inclusive'] },
      { title: 'Cancellation & refunds', fields: ['cancellation_window_hours', 'refund_on_cancel_percent', 'cancellation_policy'] },
      { title: 'Description', fields: ['description'] },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, maxLength: 255 },
      { name: 'slug', label: 'Slug', type: 'slug', required: true, slugFrom: 'title' },
      { name: 'category', label: 'Category', type: 'select', required: true, options: EVENT_CATEGORIES },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: opts({ draft: 'Draft', published: 'Published', cancelled: 'Cancelled', archived: 'Archived' }),
        hint: 'Cancelling cancels every registration, refunds paid places in full and emails each guest. It cannot be undone.',
      },
      { name: 'is_featured', label: 'Featured', type: 'boolean' },
      { name: 'summary', label: 'Summary', type: 'textarea', maxLength: 2000 },
      { name: 'cover_media_id', label: 'Cover image', type: 'media' },
      { name: 'timezone', label: 'Venue time zone', type: 'timezone', required: true },
      { name: 'city_id', label: 'City', type: 'relation', relation: { path: '/admin/cities', label: 'name' } },
      { name: 'starts_at', label: 'Starts', type: 'datetime', required: true, timezoneField: 'timezone' },
      { name: 'ends_at', label: 'Ends', type: 'datetime', required: true, timezoneField: 'timezone' },
      { name: 'venue', label: 'Venue', type: 'text', maxLength: 255 },
      { name: 'address', label: 'Address', type: 'text', maxLength: 500, hint: 'Shown on the public page.' },
      { name: 'registration_mode', label: 'Registration', type: 'select', required: true, options: opts({ open: 'Open registration', application: 'By application', invitation: 'By invitation', closed: 'Closed' }) },
      { name: 'registration_opens_at', label: 'Registration opens', type: 'datetime', timezoneField: 'timezone', hint: 'Leave empty to open immediately.' },
      { name: 'registration_closes_at', label: 'Registration closes', type: 'datetime', timezoneField: 'timezone', hint: 'Leave empty to close when the gathering starts.' },
      { name: 'seat_quota', label: 'Places', type: 'number', min: 1, hint: 'Leave empty for no limit. Unpaid reservations hold a place only until their payment window ends.' },
      { name: 'waitlist_enabled', label: 'Offer a waitlist when full', type: 'boolean', hint: 'Freed places are offered to waitlisted guests in order, with a time-limited payment link.' },
      { name: 'prices', label: 'Contribution per guest', type: 'prices', hint: 'One price per currency; no automatic conversion. Leave empty for no charge.' },
      { name: 'tax_label', label: 'Tax label', type: 'text', maxLength: 60, hint: 'Shown on receipts, e.g. GST or VAT. Confirm with your accountant.' },
      { name: 'tax_rate_bp', label: 'Tax rate (basis points)', type: 'number', min: 0, max: 5000, hint: '100 basis points = 1%. 1800 = 18%.' },
      { name: 'tax_inclusive', label: 'Prices include tax', type: 'boolean' },
      { name: 'cancellation_window_hours', label: 'Refundable cancellation until (hours before)', type: 'number', min: 0, max: 2160 },
      { name: 'refund_on_cancel_percent', label: 'Refund on timely cancellation (%)', type: 'number', min: 0, max: 100 },
      { name: 'cancellation_policy', label: 'Cancellation policy (shown to guests)', type: 'textarea', maxLength: 5000 },
      { name: 'requirements', label: 'Requirements', type: 'textarea', maxLength: 5000 },
      { name: 'description', label: 'Description', type: 'richtext' },
    ],
  },
  {
    key: 'audio',
    endpoint: '/admin/audio',
    title: 'Audio library',
    singular: 'Recording',
    permission: 'content.manage',
    group: 'Content',
    description: 'Public recordings are open to everyone; client recordings require an active booking or approved application; private recordings are never listed.',
    search: true,
    filters: [
      { name: 'access', label: 'Access', options: opts({ public: 'Public', clients: 'Clients', private: 'Private' }) },
      { name: 'status', label: 'Status', options: PUBLISH },
    ],
    titleOf: (r) => String(r.title),
    defaults: { status: 'draft', access: 'clients', category: 'guided_meditation' },
    panels: [AudioFilePanel],
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'category', label: 'Category', render: (r) => AUDIO_CATEGORIES.find((c) => c.value === r.category)?.label ?? String(r.category) },
      { key: 'access', label: 'Access', render: (r) => <Badge tone={r.access === 'public' ? 'blue' : r.access === 'clients' ? 'gold' : 'muted'}>{String(r.access)}</Badge> },
      { key: 'has_file', label: 'File', render: (r) => (r.has_file ? <Badge tone="green">Uploaded</Badge> : <Badge tone="red">Missing</Badge>) },
      { key: 'status', label: 'Status', render: (r) => status(r) },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, maxLength: 255 },
      { name: 'slug', label: 'Slug', type: 'slug', required: true, slugFrom: 'title' },
      { name: 'category', label: 'Category', type: 'select', required: true, options: AUDIO_CATEGORIES },
      { name: 'access', label: 'Access', type: 'select', required: true, options: opts({ public: 'Public', clients: 'Clients only', private: 'Private (unlisted)' }) },
      { name: 'status', label: 'Status', type: 'select', required: true, options: PUBLISH },
      { name: 'duration_seconds', label: 'Duration (seconds)', type: 'number', min: 1 },
      { name: 'description', label: 'Description', type: 'textarea', maxLength: 5000 },
      { name: 'cover_media_id', label: 'Cover image', type: 'media' },
      { name: 'is_featured', label: 'Featured on home page', type: 'boolean' },
      { name: 'sort_order', label: 'Sort order', type: 'number' },
    ],
  },
  {
    key: 'faqs',
    endpoint: '/admin/faqs',
    title: 'FAQs',
    singular: 'FAQ',
    permission: 'content.manage',
    group: 'Content',
    filters: [{ name: 'is_published', label: 'Published', options: YES_NO }],
    titleOf: (r) => String(r.question),
    defaults: { is_published: false },
    columns: [
      { key: 'question', label: 'Question' },
      { key: 'is_published', label: 'Status', render: (r) => flag(asBool(r.is_published), 'Published', 'Hidden') },
      { key: 'sort_order', label: 'Order' },
    ],
    fields: [
      { name: 'question', label: 'Question', type: 'text', required: true, maxLength: 500, wide: true },
      { name: 'answer', label: 'Answer', type: 'textarea', required: true, maxLength: 5000 },
      { name: 'service_id', label: 'Service', type: 'relation', relation: { path: '/admin/services', label: 'title', emptyLabel: 'General' } },
      { name: 'sort_order', label: 'Sort order', type: 'number' },
      { name: 'is_published', label: 'Published', type: 'boolean' },
    ],
  },
  {
    key: 'testimonials',
    endpoint: '/admin/testimonials',
    title: 'Testimonials',
    singular: 'Testimonial',
    permission: 'content.manage',
    group: 'Content',
    notice: <Notice tone="warn">Publish only genuine words from real clients, with their written authorisation on file. A consent reference is required before publishing.</Notice>,
    filters: [{ name: 'is_published', label: 'Published', options: YES_NO }],
    titleOf: (r) => String(r.attribution),
    defaults: { is_published: false, is_authorized: false },
    columns: [
      { key: 'attribution', label: 'Attribution' },
      { key: 'quote', label: 'Quote', render: (r) => <span className="line-clamp-2 max-w-md">{String(r.quote)}</span> },
      { key: 'is_authorized', label: 'Authorised', render: (r) => flag(asBool(r.is_authorized), 'Authorised', 'Not authorised') },
      { key: 'is_published', label: 'Status', render: (r) => flag(asBool(r.is_published), 'Published', 'Hidden') },
    ],
    fields: [
      { name: 'quote', label: 'Quote', type: 'textarea', required: true, maxLength: 2000 },
      { name: 'attribution', label: 'Attribution', type: 'text', required: true, maxLength: 190, hint: 'As the client agreed to be named, e.g. initials only.' },
      { name: 'role', label: 'Role', type: 'text', maxLength: 190 },
      { name: 'consent_reference', label: 'Consent reference', type: 'text', maxLength: 190, hint: 'Where the written authorisation is kept, e.g. a document or email reference.' },
      { name: 'is_authorized', label: 'Client has authorised publication in writing', type: 'boolean' },
      { name: 'is_published', label: 'Published', type: 'boolean' },
      { name: 'sort_order', label: 'Sort order', type: 'number' },
    ],
  },
  {
    key: 'seo',
    endpoint: '/admin/seo',
    title: 'SEO metadata',
    singular: 'SEO override',
    permission: 'seo.manage',
    group: 'Content',
    description: 'Per-path overrides for titles, descriptions, canonical URLs and robots directives.',
    search: true,
    titleOf: (r) => String(r.path),
    defaults: { robots: 'index,follow' },
    columns: [
      { key: 'path', label: 'Path' },
      { key: 'title', label: 'Title' },
      { key: 'robots', label: 'Robots' },
    ],
    fields: [
      { name: 'path', label: 'Path', type: 'text', required: true, maxLength: 255, hint: 'e.g. /practice/executive-mind-architecture' },
      { name: 'title', label: 'Title', type: 'text', maxLength: 255, hint: 'About 50–60 characters.' },
      { name: 'description', label: 'Description', type: 'textarea', rows: 3, maxLength: 500, hint: 'About 150–160 characters.' },
      { name: 'canonical', label: 'Canonical URL', type: 'url', maxLength: 500 },
      { name: 'robots', label: 'Robots', type: 'select', options: opts({ 'index,follow': 'index, follow', 'noindex,follow': 'noindex, follow', 'noindex,nofollow': 'noindex, nofollow', 'index,nofollow': 'index, nofollow' }) },
      { name: 'og_image_media_id', label: 'Social sharing image', type: 'media' },
    ],
  },

  // ------------------------------------------------------------------ system
  {
    key: 'email-templates',
    endpoint: '/admin/email-templates',
    title: 'Email templates',
    singular: 'Email template',
    permission: 'settings.manage',
    group: 'System',
    description: 'Copy for each automatic message. Templates are tied to notification types and cannot be added or removed.',
    search: true,
    canCreate: false,
    canDelete: false,
    titleOf: (r) => String(r.name),
    panels: [EmailTemplatePanel],
    columns: [
      { key: 'name', label: 'Template' },
      { key: 'slug', label: 'Type', render: (r) => <code className="text-xs text-slate-400">{String(r.slug)}</code> },
      { key: 'subject', label: 'Subject' },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true, maxLength: 190 },
      { name: 'subject', label: 'Subject', type: 'text', required: true, maxLength: 255 },
      { name: 'body_html', label: 'HTML body', type: 'code', required: true, rows: 18, hint: 'Scripts, forms, embeds and inline event handlers are rejected.' },
      { name: 'body_text', label: 'Plain-text body', type: 'code', rows: 10, hint: 'Optional. Generated from the HTML when empty.' },
    ],
  },
]

export const RESOURCE_BY_KEY = new Map(RESOURCES.map((r) => [r.key, r]))
